services:
  blog:
    image: ruby:3.3.2
    ports:
      - 80:80
    environment:
      - BUNDLE_PATH=vendor/bundle
    volumes:
      - .:/src
    working_dir: /src
    command: bundle exec jekyll s --host=0.0.0.0 --port=80
